### ISSUE TITLE
Crashes when loading with Dye Depot

### ISSUE THREAD

**Issue by M-rld** [Tellios-Projects/Mint#17]
`Caused by: java.lang.IllegalArgumentException: Duplicate entry on id 16: current=maroon, previous=mint`
seems to be because both this mod and [dye depot](https://modrinth.com/mod/dye-depot) have maroon, mint, navy, and indigo dyes

**Comment by Leafenzo** [comment]
Intended behavior, currently the mod is incompatible with Dye Depot. 

If they wanna work with us to fix it, or if when we eventually make architectural changes to how this mod edits the dye enum then we could fix this but for now this is de-prioritized.
